theme = "iceberg"

[icons]
name = "material-nf"
[icons.overrides]
volume_muted = "\uf210"
volume_empty = "\uf20d"
volume_half = "\uf20e"
volume_full = "\uf20f"
net_wired = "\uf18f"
net_wireless = "\uf1bd"
music = "\uf1ac"

[[block]]
block = "focused_window"
show_marks = "visible"
max_width = 70

[[block]]
block = "music"
buttons = ["play", "next"]
format = "{title}"
[block.theme_overrides]
info_bg = "#A092C8"

[[block]]
block = "load"
icons_format = " \uf100 "

[[block]]
block = "temperature"
collapsed = false
chip = "coretemp-isa-0000"
format = "{average}"
icons_format = " \uf1ee "
interval = 5

[[block]]
block = "sound"
on_click = "pavucontrol"

[[block]]
block = "networkmanager"
device_format = "{icon}{name} {ap}"
on_click = "networkmanager_dmenu"

[[block]]
block = "time"
icons_format = " "
interval = 60
format = "%a %d/%m %R"
on_click = "wldash"
