fallback = ''

[matching]
"/ - NVIM/" = ""
"launcher" = ""
"emacs" = "Em"
"mu4e" = ""
"org.wezfurlong.wezterm" = ">_"
"/Private Browsing/" = ""
"firefox" = ""
"meet" = ""
"ranger" = ""
"xplr" = ""
"gthumb" = ""
"mirage" = ""
"menu" = ""
"fragments" = ""
"mpv" = ""
"ncmpcpp" = ""
"discord" = "ﭮ"
"org.pwmt.zathura" = ""
